version: "3"
services:
  gitbucket:
    container_name: gitbucket
    build:
      context: ./gitbucket
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
    volumes:
      - ./gitbucket-data:/gitbucket
    depends_on:
      - db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --log-timestamps=SYSTEM
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gitbucket
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backup:
    container_name: backup
    build:
      context: ./backup
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    environment:
      - TZ=Asia/Tokyo
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    volumes:
      - ./gitbucket-data:/mnt/from
      - /mnt/backup_gitbucket:/mnt/to
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
